### ISSUE TITLE
The bottom-rightmost graphic of tilesheets cannot be read.

### ISSUE THREAD

**Issue by seisatsu** [Driftwood2D/Driftwood#205]
Checkout the new branch, commit 6c5ecf8, and run with ```bin/driftwood --path new``` to run the testing world. With this simple code, the game will crash if the player walks more than a few tiles to the right on any layer.

Engine Log:

```
[seisatsu@voidstar Driftwood]$ bin/driftwood --path new
Driftwood 2D
Starting up...
[0] INFO: Path: appended: data/new
[0] INFO: Path: rebuilt
[0] INFO: Audio: initialized mixer output
[0] INFO: Audio: initialized mixer audio format support: ogg
[0] INFO: Script: loaded: init.py
[0] INFO: Script: loaded: Stageshow/viewport.py
[0] INFO: Script: loaded: Stageshow/lighting.py
[0] INFO: Resource: requested: area1.json
[0] INFO: Cache: uploaded: area1.json
[0] INFO: Light: reset
[0] INFO: Resource: requested: area1_background.png
[0] INFO: Cache: uploaded: area1_background.png
[0] INFO: Area: loaded: area1.json
[0] INFO: Resource: requested: player.json
[0] INFO: Cache: uploaded: player.json
[0] INFO: Resource: requested: player.png
[0] INFO: Cache: uploaded: player.png
[0] INFO: Entity: inserted: player.json on layer 0 at position 4, 8
[0] INFO: Script: loaded: player.py
New entity "player" with EID 0 at 64,128,0 
[0] INFO: Script: loaded: Folkdance/player.py
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 117, in <module>
  File "./driftwood.py", line 171, in _run
  File "./tickmanager.py", line 196, in _tick
  File "./tickmanager.py", line 254, in __call_callback
  File "./areamanager.py", line 159, in _tick
  File "./areamanager.py", line 188, in __build_frame
  File "./layer.py", line 262, in __getitem__
  File "./layer.py", line 293, in __get
KeyError: 189
```

**Comment by seisatsu** [comment]
This happens any time the graphic from the bottom right corner of the tilesheet is on screen.

**Comment by seisatsu** [comment]
The issue was due to a mistaken use of range() at line 288 in layer.py.
